package main

import (
	"github.com/bwmarrin/discordgo"
	"log"
	"math/rand"
	"strings"
)

var quotes = []string{"OHHH, SHOW US YOUR MUSCLES! YOU'LL BE A SOLDIER!", "OUT! OUT, DAMN YOU! I'M DONE WITH YOU! GO, RUN BACK TO WINTERFELL! I'LL HAVE YOUR HEAD ON A SPIKE!", "YES, IT'S BEEN A LONG TIME... BUT I STILL REMEMBER EVERY FACE!", "YOU'RE MY COUNCIL, COUNSEL! SPEAK SENSE TO THIS HONORABLE FOOL!", "OH, IT'S UNSPEAKABLE TO YOU? WHAT HER FATHER DID TO YOUR FAMILY, THAT WAS UNSPEAKABLE!", "IS THAT HOW YOU SPEAK TO YOUR KING??", "FORCED TO MIND THE DOOR WHILE YOUR KING EATS AND DRINKS AND SHITS AND FUCKS!", "I WARNED YOU THIS WOULD HAPPEN! BACK IN THE NORTH, I WARNED YOU, BUT YOU DIDN'T CARE TO HEAR! WELL, HEAR IT NOW!", "DID YOU EVER MAKE THE EIGHT?", "WEAR IT IN SILENCE, OR I'LL HONOR YOU AGAIN!", "GODS I WAS STRONG THEN", "IT MUST WOUND YOUR PRIDE! STANDING OUT THERE, LIKE A GLORIFIED SENTRY!", "COME, BOW BEFORE YOUR KING! BOW, YA SHITS!", "WE WERE AT WAR! NONE OF US KNEW IF WE WERE GONNA GO BACK HOME AGAIN!", "YOU'RE THE KING'S HAND! YOU'LL DO AS I COMMAND, OR I'LL FIND ME A HAND WHO WILL!", "WINE! WINE! MOOOOOOOOAR WINE!", "HE COULD HAVE LINGERED ON THE EDGE OF THE BATTLE WITH THE SMART BOYS, AND TODAY HIS WIFE WOULD BE MAKING HIM MISERABLE, HIS SONS WOULD BE INGRATES, AND HE WOULD BE WAKING THREE TIMES IN THE NIGHT TO PISS INTO A BOWL!", "THE WHORE IS PREGNANT!", "SURROUNDED BY LANNISTERS! EVERY TIME I CLOSE MY EYES I SEE THEIR BLONDE HAIR AND THEIR SMUG, SATISFIED FACES!", "THERE'S A WAR COMING, NED. I DON'T KNOW WHEN, I DON'T KNOW WHO WE'LL BE FIGHTING...BUT IT'S COMING!", "GODS WHAT A STUPID NAME!", "CAREFUL, NED! CAREFUL NOW!", "START THE DAMN JOUST BEFORE I PISS MESELF!", "WE'RE TELLING WAR STORIES! WHO WAS YOUR FIRST KILL, NOT COUNTING OLD MEN?"}

func summonCommand(s *discordgo.Session, m *discordgo.MessageCreate) {
	if strings.Contains(strings.ToUpper(m.Content), "BOBBY") {
		_, err := s.ChannelMessageSend(m.ChannelID, getBobbyBQuote())
		if err != nil {
			log.Println(err)
		}
	}
}

func getBobbyBQuote() string {
	n := rand.Intn(len(quotes))
	return quotes[n]
}
